# Generated by Django 4.1.1 on 2023-03-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("middle_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "state_of_Residence",
                    models.CharField(
                        choices=[
                            ("Abia", "Abia"),
                            ("Adamawa", "Adamawa"),
                            ("Akwa-Ibom", "Akwa-Ibom"),
                            ("Anambra", "Anambra"),
                            ("Bauchi", "Bauchi"),
                            ("Bayelsa", "Bayelsa"),
                            ("Benue", "Benue"),
                            ("Borno", "Borno"),
                            ("Cross-River", "Cross-River"),
                            ("Delta", "Delta"),
                            ("Ebonyi", "Ebonyi"),
                            ("Edo", "Edo"),
                            ("Ekiti", "Ekiti"),
                            ("Enugu", "Enugu"),
                            ("Gombe", "Gombe"),
                            ("Imo", "Imo"),
                            ("Jigawa", "Jigawa"),
                            ("Kaduna", "Kaduna"),
                            ("Kano", "Kano"),
                            ("Katsina", "Katsina"),
                            ("Kebbi", "Kebbi"),
                            ("Kogi", "Kogi"),
                            ("Kwara", "Kwara"),
                            ("Lagos", "Lagos"),
                            ("Nasarawa", "Nasarawa"),
                            ("Niger", "Niger"),
                            ("Ogun", "Ogun"),
                            ("Ondo", "Ondo"),
                            ("Osun", "Osun"),
                            ("Oyo", "Oyo"),
                            ("Plateau", "Plateau"),
                            ("Rivers", "Rivers"),
                            ("Sokoto", "Sokoto"),
                            ("Taraba", "Taraba"),
                            ("Yobe", "Yobe"),
                            ("Zamfara", "Zamfara"),
                            ("Abuja", "Abuja"),
                        ],
                        default="Edo",
                        max_length=15,
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("Arts", "Arts"),
                            ("Agriculture", "Agriculture"),
                            ("Basic Medical Sciences", "Basic Medical Sciences"),
                            ("Dentistry", "Dentistry"),
                            ("Education", "Education"),
                            ("Engineering", "Engineering"),
                            ("Environmental Sciences", "Environmental Sciences"),
                            ("Law", "Law"),
                            ("Management Science", "Management Science"),
                            ("Pharmacy", "Pharmacy"),
                            ("Physical Science", "Physical Science"),
                            ("Social Science", "Social Science"),
                            (
                                "School of Medical Sciences",
                                "School of Medical Sciences",
                            ),
                            ("College of Medicine", "College of Medicine"),
                            ("Veterinary Medicine", "Veterinary Medicine"),
                        ],
                        max_length=30,
                    ),
                ),
                ("department", models.CharField(max_length=150)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("1", "100 Level"),
                            ("2", "200 level"),
                            ("3", "300 level"),
                            ("4", "400 level"),
                            ("5", "500 level"),
                            ("6", "600 level"),
                            ("other", "> 600 level"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("phone_number", models.CharField(max_length=11)),
            ],
        ),
    ]
