# Generated by Django 4.1.1 on 2023-06-02 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("Arts", "Arts"),
                            ("Agriculture", "Agriculture"),
                            ("Basic Medical Sciences", "Basic Medical Sciences"),
                            ("Dentistry", "Dentistry"),
                            ("Education", "Education"),
                            ("Engineering", "Engineering"),
                            ("Environmental Sciences", "Environmental Sciences"),
                            ("Law", "Law"),
                            ("Life Sciences", "Life Sciences"),
                            ("Management Science", "Management Science"),
                            ("Pharmacy", "Pharmacy"),
                            ("Physical Science", "Physical Science"),
                            ("Social Science", "Social Science"),
                            ("College of Medicine", "College of Medicine"),
                            ("Veterinary Medicine", "Veterinary Medicine"),
                        ],
                        max_length=30,
                    ),
                ),
                ("department", models.CharField(max_length=150)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100", "100 Level"),
                            ("200", "200 level"),
                            ("300", "300 level"),
                            ("400", "400 level"),
                            ("500", "500 level"),
                            ("600", "600 level"),
                            ("other", "> 600 level"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
            ],
        ),
    ]
