# Generated by Django 4.1.1 on 2023-06-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("Arts", "Arts"),
                    ("Agriculture", "Agriculture"),
                    ("Basic Medical Sciences", "Basic Medical Sciences"),
                    ("Dentistry", "Dentistry"),
                    ("Education", "Education"),
                    ("Engineering", "Engineering"),
                    ("Environmental Sciences", "Environmental Sciences"),
                    ("Law", "Law"),
                    ("Life Sciences", "Life Sciences"),
                    ("Management Science", "Management Science"),
                    ("Pharmacy", "Pharmacy"),
                    ("Physical Science", "Physical Science"),
                    ("Social Science", "Social Science"),
                    ("College of Medicine", "College of Medicine"),
                    ("Veterinary Medicine", "Veterinary Medicine"),
                    ("Nil", "Nil"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100 Level"),
                    ("200", "200 level"),
                    ("300", "300 level"),
                    ("400", "400 level"),
                    ("500", "500 level"),
                    ("600", "600 level"),
                    ("other", "> 600 level"),
                    ("Nil", "Nil"),
                ],
                max_length=30,
            ),
        ),
    ]
