# Generated by Django 4.1.1 on 2023-03-09 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_registration_state_of_residence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100 Level"),
                    ("200", "200 level"),
                    ("300", "300 level"),
                    ("400", "400 level"),
                    ("500", "500 level"),
                    ("600", "600 level"),
                    ("other", "> 600 level"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
    ]
