# Generated by Django 4.1.1 on 2023-04-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_registration_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("Arts", "Arts"),
                    ("Agriculture", "Agriculture"),
                    ("Basic Medical Sciences", "Basic Medical Sciences"),
                    ("Dentistry", "Dentistry"),
                    ("Education", "Education"),
                    ("Engineering", "Engineering"),
                    ("Environmental Sciences", "Environmental Sciences"),
                    ("Law", "Law"),
                    ("Life Sciences", "Life Sciences"),
                    ("Management Science", "Management Science"),
                    ("Pharmacy", "Pharmacy"),
                    ("Physical Science", "Physical Science"),
                    ("Social Science", "Social Science"),
                    ("College of Medicine", "College of Medicine"),
                    ("Veterinary Medicine", "Veterinary Medicine"),
                ],
                max_length=30,
            ),
        ),
    ]
